services:
  expo:
    build:
      context: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
